# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Progen < Formula
  desc "Project Generator CLI"
  homepage "https://github.com/sivaprasadreddy/progen"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sivaprasadreddy/progen/releases/download/v0.0.7/progen_darwin_x86_64.tar.gz"
      sha256 "6ba9dd8bd0083d9c565d24774b81d522980969c6d35d3fb16ede07fb333ba5f5"

      def install
        bin.install "progen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sivaprasadreddy/progen/releases/download/v0.0.7/progen_darwin_arm64.tar.gz"
      sha256 "3f40f82d5653a8ed073e102e8b2a11d69515637c5fdd976fd9de75262be2772a"

      def install
        bin.install "progen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sivaprasadreddy/progen/releases/download/v0.0.7/progen_linux_x86_64.tar.gz"
        sha256 "0629be5277c02b4f0f1c1760d4c6fc0140bc020051029713f64e5def958418f3"

        def install
          bin.install "progen"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sivaprasadreddy/progen/releases/download/v0.0.7/progen_linux_arm64.tar.gz"
        sha256 "61d573032d565edae33fb65b5edaa06199f6433bc000f3e3432849aaeaa2a7f9"

        def install
          bin.install "progen"
        end
      end
    end
  end

  test do
    system "#{bin}/progen --version"
  end
end
