# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Progen < Formula
  desc "Project Generator CLI"
  homepage "https://github.com/sivaprasadreddy/progen"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sivaprasadreddy/progen/releases/download/v0.0.5/progen_darwin_arm64.tar.gz"
      sha256 "2a12d6375d58a381d4ea27347e7783ecee7c419dc97645a5092110f9cf820af5"

      def install
        bin.install "progen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sivaprasadreddy/progen/releases/download/v0.0.5/progen_darwin_x86_64.tar.gz"
      sha256 "68438de7dbb4ebc0be21744a6eccab7fec4d37261e2556fa8510546c9183b568"

      def install
        bin.install "progen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sivaprasadreddy/progen/releases/download/v0.0.5/progen_linux_arm64.tar.gz"
      sha256 "493f5d58a5ca9e33e9e2bc7c5bda301a8595ec7921989f953c97a1ffb99ee402"

      def install
        bin.install "progen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sivaprasadreddy/progen/releases/download/v0.0.5/progen_linux_x86_64.tar.gz"
      sha256 "c2dcfe429789f29daf4558b239f92c2e65a4a1c877a9e8df566db99ac5163591"

      def install
        bin.install "progen"
      end
    end
  end

  test do
    system "#{bin}/progen --version"
  end
end
